description: "Example of using P2PFL with the MNIST dataset, a collection of handwritten digits commonly used for training image processing systems."

# Remote loggers configuration (optional)
remote_loggers:
  # wandb_api_key: "your-api-key"
  # wandb_project: "p2pfl-mnist"
  # p2pfl_web_url: "https://your-server.com"
  # p2pfl_web_key: "your-api-key"

# Defines network setup
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 50
  topology: null   # Network topology: "line", "ring", "star", "full", null for custom
  additional_connections:
    # - [0, 2]              # Connect node 0 to Node 2 (indices)
    # - [1, 3]              # Connect node 1 to Node 3 (indices)
    - [0, 1]
    - [0, 2]
    - [0, 3]
    - [0, 4]
    - [1, 2]
    - [1, 3]
    - [1, 4]
    - [1, 5]
    - [2, 3]
    - [2, 4]
    - [2, 5]
    - [2, 6]
    - [3, 4]
    - [3, 5]
    - [3, 6]
    - [3, 7]
    - [4, 5]
    - [4, 6]
    - [4, 7]
    - [4, 8]
    - [5, 6]
    - [5, 7]
    - [5, 8]
    - [5, 9]
    - [6, 7]
    - [6, 8]
    - [6, 9]
    - [6, 10]
    - [7, 8]
    - [7, 9]
    - [7, 10]
    - [7, 11]
    - [8, 9]
    - [8, 10]
    - [8, 11]
    - [8, 12]
    - [9, 10]
    - [9, 11]
    - [9, 12]
    - [9, 13]
    - [10, 11]
    - [10, 12]
    - [10, 13]
    - [10, 14]
    - [11, 12]
    - [11, 13]
    - [11, 14]
    - [11, 15]
    - [12, 13]
    - [12, 14]
    - [12, 15]
    - [12, 16]
    - [13, 14]
    - [13, 15]
    - [13, 16]
    - [13, 17]
    - [14, 15]
    - [14, 16]
    - [14, 17]
    - [14, 18]
    - [15, 16]
    - [15, 17]
    - [15, 18]
    - [15, 19]
    - [16, 17]
    - [16, 18]
    - [16, 19]
    - [16, 20]
    - [17, 18]
    - [17, 19]
    - [17, 20]
    - [17, 21]
    - [18, 19]
    - [18, 20]
    - [18, 21]
    - [18, 22]
    - [19, 20]
    - [19, 21]
    - [19, 22]
    - [19, 23]
    - [20, 21]
    - [20, 22]
    - [20, 23]
    - [20, 24]
    - [21, 22]
    - [21, 23]
    - [21, 24]
    - [21, 25]
    - [22, 23]
    - [22, 24]
    - [22, 25]
    - [22, 26]
    - [23, 24]
    - [23, 25]
    - [23, 26]
    - [23, 27]
    - [24, 25]
    - [24, 26]
    - [24, 27]
    - [24, 28]
    - [25, 26]
    - [25, 27]
    - [25, 28]
    - [25, 29]
    - [26, 27]
    - [26, 28]
    - [26, 29]
    - [26, 30]
    - [27, 28]
    - [27, 29]
    - [27, 30]
    - [27, 31]
    - [28, 29]
    - [28, 30]
    - [28, 31]
    - [28, 32]
    - [29, 30]
    - [29, 31]
    - [29, 32]
    - [29, 33]
    - [30, 31]
    - [30, 32]
    - [30, 33]
    - [30, 34]
    - [31, 32]
    - [31, 33]
    - [31, 34]
    - [31, 35]
    - [32, 33]
    - [32, 34]
    - [32, 35]
    - [32, 36]
    - [33, 34]
    - [33, 35]
    - [33, 36]
    - [33, 37]
    - [34, 35]
    - [34, 36]
    - [34, 37]
    - [34, 38]
    - [35, 36]
    - [35, 37]
    - [35, 38]
    - [35, 39]
    - [36, 37]
    - [36, 38]
    - [36, 39]
    - [36, 40]
    - [37, 38]
    - [37, 39]
    - [37, 40]
    - [37, 41]
    - [38, 39]
    - [38, 40]
    - [38, 41]
    - [38, 42]
    - [39, 40]
    - [39, 41]
    - [39, 42]
    - [39, 43]
    - [40, 41]
    - [40, 42]
    - [40, 43]
    - [40, 44]
    - [41, 42]
    - [41, 43]
    - [41, 44]
    - [41, 45]
    - [42, 43]
    - [42, 44]
    - [42, 45]
    - [42, 46]
    - [43, 44]
    - [43, 45]
    - [43, 46]
    - [43, 47]
    - [44, 45]
    - [44, 46]
    - [44, 47]
    - [44, 48]
    - [45, 46]
    - [45, 47]
    - [45, 48]
    - [45, 49]
    - [46, 47]
    - [46, 48]
    - [46, 49]
    - [0, 46]
    - [47, 48]
    - [47, 49]
    - [0, 47]
    - [1, 47]
    - [48, 49]
    - [0, 48]
    - [1, 48]
    - [2, 48]
    - [0, 49]
    - [1, 49]
    - [2, 49]
    - [3, 49]

# Defines experiment settings
experiment:
  name: "my_experiment"
  rounds: 100
  epochs: 1
  trainset_size: 10
  seed: 666
  wait_timeout: 600 # Timeout in minutes for wait_to_finish (default: 60 minutes)

  # Dataset settings
  dataset:
    source: "huggingface" # Dataset source: "huggingface", "csv", etc.
    name: "p2pfl/MNIST"
    batch_size: 128
    # Uncomment and adjust this to use transforms
    #transforms:
    #  package: "XXXX"
    #  function: "XX"
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "RandomIIDPartitionStrategy"
      reduced_dataset: false # For testing purposes
      reduction_factor: 10

      params: {} # No parameters needed for random partitioning

  # Learning algorithm configuration
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch" # mlp_pytorch | mlp_tensorflow
    model_build_fn: "model_build_fn"
    params: {}
    # Learning algorithm parameters (algorithm-specific)
    #compression:
    #ptq:
    #  dtype: "int8"
    #topk:
    #  k: 0.1
    #zlib:
    #  level: 6

  # Aggregation algorithm configuration
  aggregator:
    package: "p2pfl.learning.aggregators.dfedadp"
    aggregator: "DFedAdp"
    params: # Aggregator parameters (algorithm-specific)
      learning_rate: 0.001
      decay_rate: 0.95 # the reduce learning_rate each round
      min_learning_rate: 0.0001 # minimum of learning rate after decay
      alpha : 2.0 #ALPHA for glompetz function
      # log_dfedadp_params: true # specific log in dfedadp

# General experiment settings
settings:
  general:
    log_level: "INFO" # Logging verbosity: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
    grpc_timeout: 2
    disable_ray: False

  SSL:
    use_ssl: false
    CA_CRT: None
    SERVER_CRT: None
    CLIENT_CRT: None
    SERVER_KEY: None
    CLIENT_KEY: None
  heartbeat:
    period: 2
    timeout: 300
    wait_convergence: 300
    exclude_beat_logs: true
  gossip:
    period: 1
    ttl: 10
    messages_per_period: 200
    amount_last_messages_saved: 1000
    models_period: 1
    models_per_round: 4
    exit_on_x_equal_rounds: 50
  training:
    vote_timeout: 300
    aggregation_timeout: 300

# Profiling configuration
profiling:
  enabled: false
  measure_time: true
  output_dir: "profile/mnist"
