description: "Example of using P2PFL with the MNIST dataset, a collection of handwritten digits commonly used for training image processing systems."

# Remote loggers configuration (optional)
remote_loggers:
  # wandb_api_key: "your-api-key"
  # wandb_project: "p2pfl-mnist"
  # p2pfl_web_url: "https://your-server.com"
  # p2pfl_web_key: "your-api-key"

# Defines network setup
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 30
  topology: null   # Network topology: "line", "ring", "star", "full", null for custom
  additional_connections:
    # - [0, 2]              # Connect node 0 to Node 2 (indices)
    # - [1, 3]              # Connect node 1 to Node 3 (indices)
    - [0, 1]
    - [0, 3]
    - [0, 4]
    - [0, 6]
    - [0, 11]
    - [0, 20]
    - [0, 23]
    - [1, 2]
    - [1, 4]
    - [1, 7]
    - [1, 8]
    - [1, 24]
    - [2, 3]
    - [2, 5]
    - [2, 16]
    - [2, 21]
    - [2, 23]
    - [2, 28]
    - [3, 4]
    - [3, 16]
    - [3, 17]
    - [3, 18]
    - [3, 19]
    - [3, 26]
    - [4, 5]
    - [4, 13]
    - [4, 14]
    - [5, 6]
    - [5, 7]
    - [5, 12]
    - [5, 16]
    - [6, 7]
    - [6, 15]
    - [6, 17]
    - [6, 19]
    - [7, 8]
    - [7, 9]
    - [7, 22]
    - [8, 9]
    - [8, 10]
    - [8, 14]
    - [8, 20]
    - [8, 22]
    - [8, 23]
    - [9, 10]
    - [9, 13]
    - [9, 17]
    - [9, 29]
    - [10, 11]
    - [10, 14]
    - [10, 15]
    - [10, 18]
    - [11, 12]
    - [11, 19]
    - [11, 21]
    - [11, 25]
    - [11, 27]
    - [12, 13]
    - [12, 18]
    - [12, 24]
    - [12, 25]
    - [12, 28]
    - [13, 14]
    - [13, 22]
    - [14, 15]
    - [14, 26]
    - [15, 16]
    - [15, 24]
    - [16, 17]
    - [17, 18]
    - [17, 26]
    - [17, 28]
    - [18, 19]
    - [19, 20]
    - [19, 21]
    - [20, 21]
    - [20, 27]
    - [21, 22]
    - [22, 23]
    - [23, 24]
    - [23, 25]
    - [24, 25]
    - [25, 26]
    - [26, 27]
    - [26, 29]
    - [27, 28]
    - [27, 29]
    - [28, 29]
    - [29, 0]

# Defines experiment settings
experiment:
  name: "my_experiment"
  rounds: 100
  epochs: 1
  trainset_size: 30
  seed: 666
  wait_timeout: 18000

  # Dataset settings
  dataset:
    source: "huggingface" # Dataset source: "huggingface", "csv", etc.
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "DirichletPartitionStrategy"
      reduced_dataset: false # For testing purposes
      reduction_factor: 10

      params:
        alpha: 0.5
        min_partition_size: 10
        self_balancing: false

  # Learning algorithm configuration
  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch" # mlp_pytorch | mlp_tensorflow
    model_build_fn: "model_build_fn"
    params: {}
    # Learning algorithm parameters (algorithm-specific)
    #compression:
    #ptq:
    #  dtype: "int8"
    #topk:
    #  k: 0.1
    #zlib:
    #  level: 6

  # Aggregation algorithm configuration
  aggregator:
    package: "p2pfl.learning.aggregators.fedavg"
    aggregator: "FedAvg"
    params: {} # Aggregator parameters (algorithm-specific)
      #learning_rate: 0.001
      #decay_rate: 0.95 # the reduce learning_rate each round
      #min_learning_rate: 0.0001 # minimum of learning rate after decay
      #alpha: 1.0 #ALPHA for glompetz function
      # log_dfedadp_params: true # specific log in dfedadp

# General experiment settings
settings:
  general:
    log_level: "INFO" # Logging verbosity: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
    grpc_timeout: 2
    disable_ray: False

  SSL:
    use_ssl: false
    CA_CRT: None
    SERVER_CRT: None
    CLIENT_CRT: None
    SERVER_KEY: None
    CLIENT_KEY: None
  heartbeat:
    period: 2
    timeout: 3600
    wait_convergence: 4
    exclude_beat_logs: true
  gossip:
    period: 1
    ttl: 10
    messages_per_period: 200
    amount_last_messages_saved: 1000
    models_period: 1
    models_per_round: 4
    exit_on_x_equal_rounds: 50
  training:
    vote_timeout: 30
    aggregation_timeout: 300

# Profiling configuration
profiling:
  enabled: false
  measure_time: true
  output_dir: "profile/mnist"
