description: "Fraud Detection using P2PFL with custom CSV dataset"

# Remote loggers configuration (optional)
remote_loggers:
  # wandb_api_key: "your-api-key"
  # wandb_project: "p2pfl-fraud"
  # p2pfl_web_url: "https://your-server.com"
  # p2pfl_web_key: "your-api-key"

# Defines network setup
network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 10
  topology: "ring" # Network topology: "line", "ring", "star", "full"
  additional_connections:
    - [0, 2]
    - [0, 5]
    - [1, 3]
    - [2, 7]

# Defines experiment settings
experiment:
  name: "fraud_detection_experiment"
  rounds: 10
  epochs: 1
  trainset_size: 500
  seed: 666
  wait_timeout: 60

  # Dataset settings - using local CSV files
  dataset:
    source: "csv"
    name:
      train: "p2pfl/examples/fraud/fraudTrain.csv"
      test: "p2pfl/examples/fraud/fraudTest.csv"
    batch_size: 32
    transforms:
      package: "p2pfl.examples.fraud.transforms"
      function: "get_fraud_transforms"
      params: {}
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "RandomIIDPartitionStrategy"
      params:
        label_tag: "is_fraud" # Column name for labels

  # Model configuration
  model:
    package: "p2pfl.examples.fraud.model.mlp_fraud"
    model_build_fn: "model_build_fn"
    params: {}

  # Aggregation algorithm
  aggregator:
    package: "p2pfl.learning.aggregators.fedavg"
    aggregator: "FedAvg"
    params: {}

# General settings
settings:
  general:
    log_level: "INFO"
    grpc_timeout: 2
    disable_ray: False

  SSL:
    use_ssl: false
    CA_CRT: null
    SERVER_CRT: null
    CLIENT_CRT: null
    SERVER_KEY: null
    CLIENT_KEY: null

  heartbeat:
    period: 2
    timeout: 10
    wait_convergence: 4
    exclude_beat_logs: true

  gossip:
    period: 1
    ttl: 10
    messages_per_period: 200
    amount_last_messages_saved: 1000
    models_period: 1
    models_per_round: 4
    exit_on_x_equal_rounds: 50

  training:
    vote_timeout: 60
    aggregation_timeout: 300

# Profiling
profiling:
  enabled: false
  measure_time: true
  output_dir: "profile/fraud"
